global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add more scrape targets here
  # - job_name: 'your_application'
  #   static_configs:
  #     - targets: ['app1:1234', 'app2:5678']  # Replace with your app's IPs and ports
