version: '3'
services:
  db:
    image: mysql:5.7
    ports:
    - 192.168.1.40:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    labels:
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.routers.mysql.entrypoints=mysql
